source "https://rubygems.org"

# Se você NÃO UTILIZAR GitHub Pages, descomente a linha abaixo: (deixe
# comentada se você utilizar GitHub Pages):
#gem "jekyll", "~> 4.3.2"

# Se você UTILIZAR GitHub Pages, descomente a linha abaixo (deixe
# comentada se você não utilizar GitHub Pages) e depois rode o
# comando: `bundle update github-pages`.
#gem "github-pages", group: :jekyll_plugins

# Temas disponíveis para serem utilizados:
#gem "minima", "~> 2.5"
gem "jekyll-theme-cs50", group: :jekyll_plugins, git: "https://github.com/cs50/jekyll-theme-cs50", branch: "develop"

# Plugins a serem ativados:
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
  gem "jekyll-sass-converter", "~> 2.2.0"
  #gem "github-pages", "~> 228"
end

# Windows e JRuby não tem arquivos "zoneinfo",
# entao vamos agregar tudo com a gem tzinfo-data e
# outras bibliotecas associadas:
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# "Performance-booster" para monitorar diretórios
# ao usar Windows:
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Mantém a gem `http_parser.rb` na versão `v0.6.x`
# durante os builds do JRuby, já que novas versões das gem
# não têm uma contrapartida Java:
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Usa a gem webrick para poder usar o servidor local
# durante o desenvolvimento:
gem "webrick", "~> 1.7"

# Usar o CodeRay syntax highlighter com o Kramdown:
gem "kramdown-syntax-coderay", "~> 1.0"
